= Architecture Documentation

This documents describes the implemented architecture and its rules in ArchCNL.

== Architecture Rules

[role="rule"]
Every Controller must use a View.

[role="rule"]
No View can use a Model.

[role="rule"]
No Model can use a View.

== Mapping for Concepts

[role="mapping"]
isController: (?class rdf:type famix:FamixClass) (?class famix:hasName ?name) regex(?name, '(\\w||\\W)*\\.(\\w||\\W)*Controller') -> (?class rdf:type architecture:Controller)

[role="mapping"]
isView: (?class rdf:type famix:FamixClass) (?class famix:hasName ?name) regex(?name, '(\\w||\\W)*\\.(\\w||\\W)*View') -> (?class rdf:type architecture:View)

[role="mapping"]
isModel: (?class rdf:type famix:FamixClass) (?package rdf:type famix:Namespace) (?package famix:hasName ?name) regex(?name, 'model') (?package famix:namespaceContains ?class) -> (?class rdf:type architecture:Model)

[role="mapping"]
useMapping: (?class rdf:type famix:FamixClass) (?class2 rdf:type famix:FamixClass) (?f rdf:type famix:Attribute) (?class famix:definesAttribute ?f) (?f famix:hasDeclaredType ?class2) -> (?class architecture:use ?class2)

[role="mapping"]
useMapping: (?class rdf:type famix:FamixClass) (?class2 rdf:type famix:FamixClass) (?class famix:imports ?class2) -> (?class architecture:use ?class2)